apiVersion: v1
kind: Service
metadata:
  name: quizservice
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 30000
  selector:
     app: quizdeployment
     type: quiz
